name: HarryPlugin
version: '${version}'
main: fr.silenthill99.harryplugin.Main
api-version: 1.16
authors: [ silenthill99 ]
description: Plugin pour le serveur Harry PoCraft
commands:
  menu:
    permission: group.modo-stagiaire
    permission-message: §4Vous ne pouvez pas faire ceci !
  stafftchat:
    permission: harrypocraft.staff
    permission-message: §4Vous faites pas partie du staff !
    aliases: [staff, st, s]
  fondateur:
    permission: harrypocraft.fondateur
  stagiaire:
    permission: harrypocraft.stagiaire
  carte:
  discord:
    aliases: ds
  news:
    permission: group.journaliste
    permission-message: §4Vous n'avez pas accès à cette commande !
  moderateur:
    aliases: modo
    permission: harrypocraft.modo
  hrp: